In [2]:
import pandas as pd 
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('C:/Users/User/AILabEngineers/task3/data/raw/krisha1.csv')
df.head()

,price,text,area,flat_toilets,balcony,current_floors,total_floors,ceiling,dorm,mortgage,year,type_of_house,condition,repair_status,type_of_floor,location
0,NaN,Не удается получить доступ к сайту,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Страница не найдена,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Страница не найдена,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,17900000.0,"1-комнатная квартира · 45 м² · 3/9 этаж, Кайым...",45 м²,раздельный,балкон и лоджия,3.0,9.0,NaN,NaN,NaN,2020.0,NaN,NaN,полностью,ламинат,"Астана, Нура р-н\nпоказать на карте"
4,17600000.0,"1-комнатная квартира · 39 м² · 5/7 этаж, Болек...",39 м²,совмещенный,лоджия,5.0,7.0,2.8,NaN,NaN,2019.0,кирпичный,NaN,полностью,ламинат,"Астана, Алматы р-н\nпоказать на карте"

In [4]:
for i in df['text']:
    if i in ['Не удается получить доступ к сайту', 'Страница не найдена']:
        df.drop(df[df['text'] == i].index, inplace=True)
    
df = df.reset_index(drop=True)

In [5]:
df

,price,text,area,flat_toilets,balcony,current_floors,total_floors,ceiling,dorm,mortgage,year,type_of_house,condition,repair_status,type_of_floor,location
0,17900000.0,"1-комнатная квартира · 45 м² · 3/9 этаж, Кайым...",45 м²,раздельный,балкон и лоджия,3.0,9.0,NaN,NaN,NaN,2020.0,NaN,NaN,полностью,ламинат,"Астана, Нура р-н\nпоказать на карте"
1,17600000.0,"1-комнатная квартира · 39 м² · 5/7 этаж, Болек...",39 м²,совмещенный,лоджия,5.0,7.0,2.8,NaN,NaN,2019.0,кирпичный,NaN,полностью,ламинат,"Астана, Алматы р-н\nпоказать на карте"
2,29900000.0,"2-комнатная квартира · 48.76 м² · 2/9 этаж, Жо...",48.76 м²,NaN,NaN,2.0,9.0,3.0,нет,NaN,2025.0,монолитный,черновая отделка,NaN,NaN,Астана\nпоказать на карте
3,27000000.0,"3-комнатная квартира · 85 м² · 8/12 этаж, Майл...",85 м²,раздельный,NaN,8.0,12.0,3.0,нет,NaN,2024.0,монолитный,NaN,NaN,NaN,"Астана, Алматы р-н\nпоказать на карте"
4,105000000.0,"4-комнатная квартира · 128.5 м² · 3/6 этаж, Ще...",128.5 м²,NaN,NaN,3.0,6.0,3.0,нет,NaN,2025.0,монолитный,NaN,NaN,NaN,"Алматы, Ауэзовский р-н\nпоказать на карте"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6632,13500000.0,"1-комнатная квартира · 32.9 м² · 4/4 этаж, мкр...",32.9 м²,совмещенный,NaN,4.0,4.0,NaN,нет,NaN,2010.0,NaN,свежий ремонт,NaN,линолеум,"Атырау, мкр Нурсая\nпоказать на карте"
6633,29000000.0,"2-комнатная квартира · 50 м² · 8/12 этаж, мкр ...",50 м²,NaN,NaN,8.0,12.0,NaN,NaN,NaN,2024.0,NaN,NaN,NaN,NaN,"Шымкент, Абайский р-н\nпоказать на карте"
6634,30000000.0,"3-комнатная квартира · 70 м² · 2/5 этаж, мкр Н...",70 м²,NaN,NaN,2.0,5.0,NaN,NaN,NaN,1972.0,NaN,NaN,NaN,NaN,"Караганда, Казыбек би р-н\nпоказать на карте"
6635,24500000.0,"1-комнатная квартира · 34.9 м² · 4/5 этаж, Мик...",34.9 м²,NaN,NaN,4.0,5.0,2.8,нет,NaN,2023.0,монолитный,свежий ремонт,полностью,ламинат,"Алматы, Алатауский р-н\nпоказать на карте"
6636,18000000.0,"3-комнатная квартира · 50 м² · 2/5 этаж, Новат...",50 м²,совмещенный,NaN,2.0,5.0,2.5,нет,NaN,1973.0,панельный,свежий ремонт,частично,ламинат,"Усть-Каменогорск, Ульбинский\nпоказать на карте"